---
name: tozan-ecc
on: [pull_request, push]
jobs:
  build:
    name: Build Go-${{ matrix.GOVER }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOVER: ['1.18', '1.17', '1.16']
    steps:
      - name: Setup Go-${{ matrix.GOVER }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.GOVER }}

      - name: Checking out
        uses: actions/checkout@v3

      - name: Building
        run: go build -v .

      - name: Testing
        run: go test -v ./...
